### ISSUE TITLE
error running  python -m fable_py install

### ISSUE THREAD

**Issue by pipsie100** [dbrattli/Fable.Jupyter#2]
willem@vmi542194:~/python/.venv312$ python -m fable_py install
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.01s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
[Errno 13] Permission denied: '/usr/local/share/jupyter'
Perhaps you want to install with `sudo` or `--user`?

But sudo does not work either.

**Comment by pipsie100** [comment]
C:\Windows\system32>python -m fable_py install
Traceback (most recent call last):
  File "C:\Users\Willem\anaconda3\lib\runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\Willem\anaconda3\lib\runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Users\Willem\anaconda3\lib\runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\Willem\anaconda3\lib\site-packages\fable_py\__init__.py", line 2, in <module>
    from .kernel import Fable
  File "C:\Users\Willem\anaconda3\lib\site-packages\fable_py\kernel.py", line 23, in <module>
    from ipykernel.ipkernel import IPythonKernel
  File "C:\Users\Willem\AppData\Roaming\Python\Python39\site-packages\ipykernel\__init__.py", line 2, in <module>
    from .connect import *
  File "C:\Users\Willem\AppData\Roaming\Python\Python39\site-packages\ipykernel\connect.py", line 16, in <module>
    import jupyter_client
  File "C:\Users\Willem\anaconda3\lib\site-packages\jupyter_client\__init__.py", line 8, in <module>
    from .asynchronous import AsyncKernelClient  # noqa
  File "C:\Users\Willem\anaconda3\lib\site-packages\jupyter_client\asynchronous\__init__.py", line 1, in <module>
    from .client import AsyncKernelClient  # noqa
  File "C:\Users\Willem\anaconda3\lib\site-packages\jupyter_client\asynchronous\client.py", line 6, in <module>
    from jupyter_client.channels import HBChannel
  File "C:\Users\Willem\anaconda3\lib\site-packages\jupyter_client\channels.py", line 12, in <module>
    import zmq.asyncio
  File "C:\Users\Willem\anaconda3\lib\site-packages\zmq\__init__.py", line 103, in <module>
    from zmq import backend
  File "C:\Users\Willem\anaconda3\lib\site-packages\zmq\backend\__init__.py", line 31, in <module>
    raise original_error from None
  File "C:\Users\Willem\anaconda3\lib\site-packages\zmq\backend\__init__.py", line 26, in <module>
    _ns = select_backend(first)
  File "C:\Users\Willem\anaconda3\lib\site-packages\zmq\backend\select.py", line 31, in select_backend
    mod = import_module(name)
  File "C:\Users\Willem\anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\Willem\anaconda3\lib\site-packages\zmq\backend\cython\__init__.py", line 6, in <module>
    from . import (
ImportError: DLL load failed while importing _device: The specified module could not be found.

**Comment by pipsie100** [comment]
Hello Dag, can you have a look at this issue? I have no idea how to solve.
